### ISSUE TITLE
Ript: BUG

### ISSUE THREAD

**Issue by jamieslater** [bulletproofnetworks/ript#20]
### I tried to do this:
- TBC
### I expected this to happen:
-  TBC
### I instead saw this happen:
- TBC
### These are other things I observed:
- If there are no dnat rules you get

```
* executing "sudo -p 'sudo password: ' iptables --table nat --list partition-s --verbose --numeric --line-numbers 2>&1 | egrep '^[[:digit:]]' | wc -l"
servers: ["customer-fw-02"]
[customer-fw-02] executing command
command finished in 696ms
DANGER: there are errors:

- table: nat, chain: partition-d has 0 rules

The firewall is probably broken!

Please escalate to the infrastructure team IMMEDIATELY
as an error.
```
- there are some scenarios where this is valid
- @johnf thought he has made a mistake when he saw that all in red just now

**Comment by elmobp** [comment]
Close wont do
