### ISSUE TITLE
LICENCE is contradictory

### ISSUE THREAD

**Issue by auxesis** [bulletproofnetworks/ript#23]
The first line on `LICENSE.md` currently states:

```
Copyright 2011-2012 Bulletproof Networks. All rights reserved.
```

The rest of the file then has the standard MIT licence. 

However, the `All rights reserved.` contradicts the MIT license. 

So the MIT license is valid, the `All rights reserved.` should be removed.

**Comment by jamesmollison** [comment]
Thanks LH - This has been resolved by @elmobp in Pull Request #22
